[package]
name = "fakecam"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gstreamer = "0.17.4"
gstreamer-base = "0.17.2"
gstreamer-video = "0.17.2"
gtk4 = "0.3.0"
once_cell = "1.8.0"
